name: Test

on: 
  push: 
  workflow_dispatch:

env:
  NODE_VERSION: 17.6.0
  
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache
        uses: actions/cache@v2.1.7
        env:
          cache-name: 'cache-npm-modules'
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install node modules 
        run: npm install
        
      - name: Run tests
        run: npm test
